apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
spec:
  selector:
    matchLabels:
      app: apache
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: europe-west2-docker.pkg.dev/cicdsujana-345110/my-repository/testwebsitegold:ver1
        ports:
          - containerPort: 80
